image: 'appsec4u/worker:keyid'
variables:
  ENG: 9
  DOCKER_IMAGE: 'nginx:latest'
  WEBSITE: 'https://scansuite.ru'
  COOKIES: none
  LANG: java

stages:
  - build
  - sast
  - sca
  - infra_test
  - dynamic
  - prod
before_script:
  - export DOJO_APIKEY=$DOJO_APIKEY
  - export DOJO_HOST=$DOJO_HOST
build:
  stage: build
  script:
    - echo "Building"

# SAST Section
secrets:
  stage: build
  script:
    - scansuite secrets $ENG
  allow_failure: true
sast_quick:
  stage: sast
  script:
    - scansuite sast_quick $ENG
  allow_failure: true
sast_full:
  stage: sast
  script:
    - scansuite sast_full $ENG
  allow_failure: true
sast_java:
  stage: sast
  script:
    - scansuite $LANG $ENG
  allow_failure: true


# SCA/OAST Section
dep_checks:
  stage: sca
  script:
    - scansuite dep_checks $ENG
  allow_failure: true

# Configs and docker image checks
iacs_kics:
  stage: infra_test
  script:
    - scansuite iacs_kics $ENG
  allow_failure: true
image_vulns:
  stage: infra_test
  script:
    - scansuite docker_image_scan $ENG $DOCKER_IMAGE
  allow_failure: true

# DAST Section
dast:
  stage: dynamic
  script:
    - scansuite dast_quick $ENG $WEBSITE $COOKIES
  allow_failure: true
nuclei:
  stage: dynamic
  script:
    - scansuite nuclei $ENG $WEBSITE $COOKIES
  allow_failure: true

# End of scans
production:
  stage: prod
  script:
    - id