image: 'appsec4u/worker:keyid'
variables:
  ENG: 2
  DOCKER_IMAGE: 'codeclimate/codeclimate-coffeelint'
  WEBSITE: 'https://ginandjuice.shop'
  COOKIES: none
  #COOKIES: 'session=mMtEIWn...; csrf_token=k0LKSOs...'
  #COOKIES: "Authorization: Bearer eyJhbGciOiJSUzI1N..."
  LANG: python

stages:
  - build
  - sast
  - sca
  - infra_test
  - dynamic
  - prod
before_script:
  - export DOJO_APIKEY=$DOJO_APIKEY
  - export DOJO_HOST=$DOJO_HOST
build:
  stage: build
  image: python:3.6
  before_script:
   - pip3 install --upgrade virtualenv
  script:
   - virtualenv env                       # Create a virtual environment for the python application
   - source env/bin/activate              # Activate the virtual environment
   - pip install -r requirements.txt      # Install the required third party packages as defined in requirements.txt
   - python manage.py check               # Run checks to ensure the application is working fine

# SAST Section
secrets:
  stage: build
  script:
    - scansuite secrets $ENG
  allow_failure: true
sast_quick:
  stage: sast
  script:
    - scansuite sast_quick $ENG
  allow_failure: true
sast_full:
  stage: sast
  script:
    - scansuite sast_full $ENG
  allow_failure: true
sast_python:
  stage: sast
  script:
    - scansuite $LANG $ENG
  allow_failure: true

# SCA/OAST Section
dep_checks:
  stage: sca
  script:
    - scansuite dep_checks $ENG
  allow_failure: true

# Configs and docker image checks
iacs_kics:
  stage: infra_test
  script:
    - scansuite iacs_kics $ENG
  allow_failure: true
image_vulns:
  stage: infra_test
  script:
    - scansuite docker_image_scan $ENG $DOCKER_IMAGE
  allow_failure: true

# DAST Section
dast_quick:
  stage: dynamic
  script:
    - scansuite dast_quick $ENG $WEBSITE $COOKIES
  allow_failure: true
dast_balanced:
  stage: dynamic
  script:
    - scansuite dast_balanced $ENG $WEBSITE $COOKIES
  allow_failure: true
deep_dast_scan:
  stage: dynamic
  script:
    - scansuite zap_full $ENG $WEBSITE $COOKIES
  allow_failure: true
nuclei:
  stage: dynamic
  script:
    - scansuite nuclei $ENG $WEBSITE $COOKIES
  allow_failure: true

# End of scans
production:
  stage: prod
  script:
    - id